# Generated by Django 5.2.4 on 2026-09-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.ImageField(upload_to='')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
